### ISSUE TITLE
interwiki links

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-prosemirror#12]
##ToDo

- [x] renderer Instructions -> JSON
- [x] image-titles
- [x] toolbar-button
- [x] input-rule
- [x] respective wiki-favicon in editor?
- [x] parser JSON -> Syntax

**Comment by micgro42** [comment]
Mh, links do not make much sense as a `Mark`, since they are not really formatting. I guess they are better suited as an inline `Node` with exactly one `TextNode` as content.

**Comment by micgro42** [comment]
## parseDom

Supporting copy&paste from commonly rendered wiki pages is complicated because we lack reliable information about the reference.

Further, the shortcut is only correctly coded into the `iw-`-class if it is known. All unknown shortcuts will get the class `iw-go`.
