### ISSUE TITLE
internal links

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-prosemirror#13]
##ToDo

- [x] new mark in Schema
- [x] renderer Instructions -> JSON
- [x] toolbar button
- [x] handle image titles
- [ ] input rule?
- [x] parser JSON -> SYNTAX
- [x] how to handle `$conf['useheading']`?

**Comment by micgro42** [comment]
Input rules are tracked in #63
