### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-prosemirror#20]
Footnotes are currently only rudimentarily, non-breaking implemented ( a979e5c ) and still need much work.

## ToDo:
- [ ] decide if we need/want an extra editor instance like the [example in the official documentation ](https://prosemirror.net/examples/footnote/)
- [ ] they should not be rendered inline, but at the end or on click
- [ ] they need a toolbar button to add them
- [ ] maybe add a way to remove them as well?
