### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-prosemirror#6]
what to work on next

- [ ] our white board has a list of syntax modes with checkmarks for the ones implemented, missing ones need to be added
- [ ] renderer.php contains a bunch of fixmes
- [ ] figure out how the menu bar works
- [ ] figure out how to add our own stuff to the menu bar
- [ ] figure out how to create sublists
- [ ] figure out how to change list types
- [ ] figure out how to implement custom types
- [ ] make babel/webpack create sourcemaps

**Comment by splitbrain** [comment]
Issues in here should be checked to see if they still exist, then transferred into their own issues.
